### ISSUE TITLE
Warning that custom component is using device_state_attributes

### ISSUE THREAD

**Issue by cvonk** [rsnodgrass/hass-poolmath#12]
Thanks for the integration.

Running core-2022.3.5, the log showed `custom component is using device_state_attributes`, so I renamed `device_state_attributes` to `extra_state_attributes` as in suggested in [community.home-assistant.io](https://community.home-assistant.io/t/warning-that-custom-component-is-using-device-state-attributes/376020).

Now, I get

```
poolmath: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/config/custom_components/poolmath/sensor.py", line 120, in async_update
    timestamp = await client.process_log_entry_callbacks(
  File "/config/custom_components/poolmath/client.py", line 51, in process_log_entry_callbacks
    log_entries = poolmath_soup.find_all("div", class_="logCard")
AttributeError: 'NoneType' object has no attribute 'find_all'
```

Thanks

**Comment by cvonk** [comment]
OK, I got it going, after realizing
- you need to use the `https://api.poolmathapp.com/share/xxxxxxx` type URL (the other URL returns a 301 "permanently moved" response).
- the entries are called like `sensor.pool_ph` instead of `sensor.swimming_pool_ph`

**Comment by rsnodgrass** [comment]
Resolved
