### ISSUE TITLE
poolmath: Error on device update!

### ISSUE THREAD

**Issue by philbowers** [rsnodgrass/hass-poolmath#13]
This integration hasn't worked for me in a while. I have deleted and reinstalled the poolmath HACS integration and keep getting the same error. Any suggestions?

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/config/custom_components/poolmath/sensor.py", line 120, in async_update
    timestamp = await client.process_log_entry_callbacks(
  File "/config/custom_components/poolmath/client.py", line 51, in process_log_entry_callbacks
    log_entries = poolmath_soup.find_all("div", class_="logCard")
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by rsnodgrass** [comment]
When PoolMath moved to the new https://api URLs did you update your YAML configuration?

**Comment by philbowers** [comment]
As I only am able to use this integration 3-4 months out of the year, I must had missed that change, I do apologize.
In hindsight, if nothing else, it will leave a record for anyone else having this issue. I do thank you for you work.

"Old"
`sensor:`
`platform: poolmath`
`url: 'https://troublefreepool.com/mypool/*******'`

"New"
`sensor:`
`platform: poolmath`
`url: 'https://api.poolmathapp.com/share/*******'`
