### ISSUE TITLE
Last update gave new errors

### ISSUE THREAD

**Issue by CrallH** [rsnodgrass/hass-poolmath#20]
Last update gave new error logs.
Logger: homeassistant.components.sensor
Source: custom_components/poolmath/sensor.py:182
Integration: Sensor (documentation, issues)
First occurred: 11:25:49 (1 occurrences)
Last logged: 11:25:49

poolmath: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
await task
File "/config/custom_components/poolmath/sensor.py", line 146, in async_update
timestamp = await client.process_log_entry_callbacks(
File "/config/custom_components/poolmath/client.py", line 107, in process_log_entry_callbacks
await async_callback(measurement, timestamp, value, attributes)
File "/config/custom_components/poolmath/sensor.py", line 182, in _update_sensor_callback
LOG.info(f"{self._name} {log_type}={state} (timestamp={timestamp})")
NameError: name 'log_type' is not defined

**Comment by glynweston** [comment]
I'm getting exactly the same error.

**Comment by glynweston** [comment]
My errors stopped with install of new version.
