### ISSUE TITLE
Cant update addon

### ISSUE THREAD

**Issue by CrallH** [rsnodgrass/hass-poolmath#26]
Cant update the addon.

![image](https://github.com/rsnodgrass/hass-poolmath/assets/32394267/1731908a-61e4-4b42-bc4f-d490ae6aacf3)

The log gave this:

2024-05-23 15:25:02.402 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140246085166144] Error handling message: Unknown error (unknown_error) Christian from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 232, in hacs_repository_download
await repository.update_repository(force=True)
File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
result = await function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
if manifest := await self.async_get_integration_manifest():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/hacs/repositories/integration.py", line 182, in async_get_integration_manifest
return json_loads(decode_content(response.data.content))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/json.py", line 48, in json_loads
return orjson.loads(__obj) # type:ignore[no-any-return]
^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected control character in string: line 4 column 23 (char 95)

uninstalled it to se if i could re install it but now i cant get it installed again.

this is in the log:

Felet härrör från en anpassad integration.

Logger: custom_components.hacs
Källa: custom_components/hacs/websocket/repository.py:265
integration: HACS (dokumentation, ärenden)
Inträffade först: 15:24:43 (1 händelser)
Senast loggade: 15:24:43

<Integration rsnodgrass/hass-poolmath> unexpected control character in string: line 4 column 23 (char 95)

**Comment by CrallH** [comment]
![image](https://github.com/rsnodgrass/hass-poolmath/assets/32394267/465c86b7-57ab-4126-9169-7df98041e951)
think i found it. the manifest, version line is missing ending "

**Comment by CrallH** [comment]
you need to delete the last comma on line 10 also

**Comment by rsnodgrass** [comment]
Thank you!!!

**Comment by CrallH** [comment]
> Thank you!!!

NP, happy that I could contribute with something at least 😊
